# Stage 1: Build
FROM python:3.12-slim AS build

# Set environment variables
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

# Install system dependencies
RUN apt-get update && \
    apt-get install -y --no-install-recommends gcc \
    build-essential \
    python3-psycopg2 \
    libpq-dev \
    curl && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Set the working directory
WORKDIR /app

# Copy only the requirements file and install dependencies
COPY requirements.txt /app/
RUN pip install --upgrade pip setuptools && \
    pip install --no-cache-dir -r requirements.txt

# Copy the rest of the application code
COPY . /app/

# Stage 2: Production
FROM python:3.12-slim AS production

# Set environment variables
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
ENV DJANGO_SETTINGS_MODULE=prodxcloud_multi_tenant_django.settings

# Install system dependencies
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    curl \
    libpq-dev && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Create and set the working directory
WORKDIR /app

# Copy installed dependencies from the build stage
# copy for installed gunicorn /user/local/bin/gunicorn
COPY --from=build /usr/local/lib/python3.12/site-packages /usr/local/lib/python3.12/site-packages
COPY --from=build /usr/local/bin /usr/local/bin 

# Copy the application code and static files from the build stage
COPY --from=build /app /app

# Collect static files
# RUN python manage.py collectstatic --noinput

# Run database migrations : Make sure your database connections is ready 
#RUN python manage.py makemigrations && \
#    python manage.py migrate

# Set permissions
RUN chown -R nobody:nogroup /app

# Switch to a non-root user
USER nobody

# Expose necessary ports
EXPOSE 8585
EXPOSE 80
EXPOSE 443

# Start the application with Gunicorn
CMD ["gunicorn", "--bind", "0.0.0.0:8585", "--workers", "4", "--threads", "4", "multitenantsaas.wsgi:application"]