apiVersion: v1
kind: Service
metadata:
  name: django-web-service
spec:
  selector:
    app: django-web
  type: LoadBalancer  # 외부 접속을 위해 LoadBalancer 사용
  ports:
    - port: 80
      targetPort: 8585