apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django-web
  template:
    metadata:
      labels:
        app: django-web
    spec:
      containers:
      - name: django-web
        image: 267269535421.dkr.ecr.us-east-1.amazonaws.com/django-app  # 실제 ECR 이미지 주소로 교체
        envFrom:
        - secretRef:
            name: django-env  # 필요시, 환경변수 Secret로 관리
        ports:
        - containerPort: 8585
        - containerPort: 8000
        command: ["/bin/sh", "-c"]
        args:
          - |
            python manage.py makemigrations &&
            python manage.py migrate &&
            python manage.py collectstatic --noinput &&
            gunicorn --bind 0.0.0.0:8585 prodxcloud_multi_tenant_django.wsgi:application --workers 4 --threads 4